# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  tournamentadministration:
    image: tournamentadministration
    build:
      context: .
      dockerfile: TournamentAdministration/Dockerfile
    ports:
      - 80:80
